### ISSUE TITLE
Images should be in a folder

### ISSUE THREAD

**Issue by katerberg** [Shayngo/lottery#1]
It's really hard to tell what items are for what functionality when everything is cluttered at the root folder. If the images were put into an `/images` folder, it would make it easier to keep track of what's going on.

**Comment by Gluecke** [comment]
The build system can't find android icons if they aren't in the project folder :-(.

**Comment by Gluecke** [comment]
![boo](https://cloud.githubusercontent.com/assets/14304172/9974196/5ca257ce-5e4a-11e5-94d2-d994e564fa15.PNG)
